### ISSUE TITLE
Questions about submitting files

### ISSUE THREAD

**Issue by Zhen-ao** [IBM/cdfsl-benchmark#28]
we used some of the same technology in the two technical files PDFs submitted by track1 and track2. Can the two PDFs use the same or similar descriptions(or Figure) in the public part? and Can I submit track1 and track2 documents in the same submission ?

**Comment by yunhuiguo** [comment]
Hi @123zhen123 ,  if you have a pdf for track 1 and a pdf for track 2, and the methods (descriptions) are similar, it is totally fine, but make sure to highlight that for track 2 you are leveraging unlabeled data. I am not sure if you can submit two pdfs in the same submission due to the constraints of the CMT. You can make two separate submissions in this case.
